# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

project 'FlutterModuleIOS.xcodeproj'

flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FlutterModuleIOS' do
  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
