// Autogenerated from Pigeon (v12.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class Messages {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<Object>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class Message {
    private @Nullable Long length;

    public @Nullable Long getLength() {
      return length;
    }

    public void setLength(@Nullable Long setterArg) {
      this.length = setterArg;
    }

    private @Nullable String inUpperCase;

    public @Nullable String getInUpperCase() {
      return inUpperCase;
    }

    public void setInUpperCase(@Nullable String setterArg) {
      this.inUpperCase = setterArg;
    }

    private @Nullable String inLowerCase;

    public @Nullable String getInLowerCase() {
      return inLowerCase;
    }

    public void setInLowerCase(@Nullable String setterArg) {
      this.inLowerCase = setterArg;
    }

    private @Nullable String initialText;

    public @Nullable String getInitialText() {
      return initialText;
    }

    public void setInitialText(@Nullable String setterArg) {
      this.initialText = setterArg;
    }

    public static final class Builder {

      private @Nullable Long length;

      public @NonNull Builder setLength(@Nullable Long setterArg) {
        this.length = setterArg;
        return this;
      }

      private @Nullable String inUpperCase;

      public @NonNull Builder setInUpperCase(@Nullable String setterArg) {
        this.inUpperCase = setterArg;
        return this;
      }

      private @Nullable String inLowerCase;

      public @NonNull Builder setInLowerCase(@Nullable String setterArg) {
        this.inLowerCase = setterArg;
        return this;
      }

      private @Nullable String initialText;

      public @NonNull Builder setInitialText(@Nullable String setterArg) {
        this.initialText = setterArg;
        return this;
      }

      public @NonNull Message build() {
        Message pigeonReturn = new Message();
        pigeonReturn.setLength(length);
        pigeonReturn.setInUpperCase(inUpperCase);
        pigeonReturn.setInLowerCase(inLowerCase);
        pigeonReturn.setInitialText(initialText);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(4);
      toListResult.add(length);
      toListResult.add(inUpperCase);
      toListResult.add(inLowerCase);
      toListResult.add(initialText);
      return toListResult;
    }

    static @NonNull Message fromList(@NonNull ArrayList<Object> list) {
      Message pigeonResult = new Message();
      Object length = list.get(0);
      pigeonResult.setLength((length == null) ? null : ((length instanceof Integer) ? (Integer) length : (Long) length));
      Object inUpperCase = list.get(1);
      pigeonResult.setInUpperCase((String) inUpperCase);
      Object inLowerCase = list.get(2);
      pigeonResult.setInLowerCase((String) inLowerCase);
      Object initialText = list.get(3);
      pigeonResult.setInitialText((String) initialText);
      return pigeonResult;
    }
  }

  private static class MessageApiCodec extends StandardMessageCodec {
    public static final MessageApiCodec INSTANCE = new MessageApiCodec();

    private MessageApiCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 128:
          return Message.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof Message) {
        stream.write(128);
        writeValue(stream, ((Message) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface MessageApi {

    @NonNull 
    Message getMessage(@NonNull String text);

    /** The codec used by MessageApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return MessageApiCodec.INSTANCE;
    }
    /**Sets up an instance of `MessageApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable MessageApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.pigeon_example_package.MessageApi.getMessage", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String textArg = (String) args.get(0);
                try {
                  Message output = api.getMessage(textArg);
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
