// Autogenerated from Pigeon (v12.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class PGNMessage;

@interface PGNMessage : NSObject
+ (instancetype)makeWithLength:(nullable NSNumber *)length
    inUpperCase:(nullable NSString *)inUpperCase
    inLowerCase:(nullable NSString *)inLowerCase
    initialText:(nullable NSString *)initialText;
@property(nonatomic, strong, nullable) NSNumber * length;
@property(nonatomic, copy, nullable) NSString * inUpperCase;
@property(nonatomic, copy, nullable) NSString * inLowerCase;
@property(nonatomic, copy, nullable) NSString * initialText;
@end

/// The codec used by PGNMessageApi.
NSObject<FlutterMessageCodec> *PGNMessageApiGetCodec(void);

@protocol PGNMessageApi
/// @return `nil` only when `error != nil`.
- (nullable PGNMessage *)getMessageText:(NSString *)text error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpPGNMessageApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNMessageApi> *_Nullable api);

NS_ASSUME_NONNULL_END
